export const images = {
  showerHead: require("../../assets/images/products/shower-head.jpg"),
  ethernetCable: require("../../assets/images/products/ethernet-cable.jpg"),
  zincCarnosine: require("../../assets/images/products/zinc-carnosine.jpg"),
  pepzin: require("../../assets/images/products/pepzin.jpg"),
  bedding: require("../../assets/images/products/bedding.jpg"),
  mensShirt: require("../../assets/images/products/mens-shirt.jpg"),
  aminoAcids: require("../../assets/images/products/amino-acids.jpg"),
  copperGlycinate: require("../../assets/images/products/copper-glycinate.jpg"),
  camera: require("../../assets/images/products/camera.jpg"),
  dish: require("../../assets/images/products/dish.jpg"),
  keyboard: require("../../assets/images/products/keyboard.jpg"),
  jacket: require("../../assets/images/products/jacket.jpg"),
  lightBulbs: require("../../assets/images/products/light-bulbs.jpg"),
  handCream: require("../../assets/images/products/hand-cream.jpg"),
  comforterNavy: require("../../assets/images/products/comforter-navy.jpg"),
  comforterBeige: require("../../assets/images/products/comforter-beige.jpg"),
  blanket: require("../../assets/images/products/blanket.jpg"),
  comforterGreen: require("../../assets/images/products/comforter-green.jpg"),
};
